- foo_015a_global_hunger_index/README.md
- foo_015a_global_hunger_index/foo_015a_global_hunger_index.py
added python script for foo_015a
> foo_015a add python script

- foo_015a_global_hunger_index/README.md
> newreadme for foo_015a

- ene_021a_renewable_energy_consumption/README
- ene_021a_renewable_energy_consumption/ene_021a_renewable_energy_consumption.py
intial commit for ene_021a_renewable_energy_consumption
> initial commit for ene_021a_renewable_energy_consumption

- ene_021a_renewable_energy_consumption/README.md
- ene_029a_energy_intensity/README.md
- ene_029a_energy_intensity/ene_029a_energy_intensity.py
fixed README.md for ene_021a and added ene_029a
> fixed ene_021a README.md and added ene_029a

- ene_031a_solar_irradiance/README.md
> solar irradiance documentation

- ocn_005_historical_cyclone_intensity/README.md
- ocn_005_historical_cyclone_intensity/ocn_005_historical_cyclone_intensity_processing.py
- ocn_007_coral_bleaching_monitoring/README.md
- ocn_009_sea_surface_temperature_variability/README.md
Scripts work as they appear in this branch. Had to make a minor tweak or two based on yesterday's revisions.
> README files for first ocn datasets

- cli_049_rw1_dash_pik_historical_emissions/README.md
> cli_049_fix_python_link

- bio_004a_coral_reef_locations/README.md
- bio_021a_terrestrial_ecoregions/README.md
- bio_041_rw1_ocean_health_index/README.md
- cit_022_rw1_road_traffic_death_rates/README.md
- cit_029_rw1_municipal_waste/README.md
- cli_049_rw1_dash_pik_historical_emissions/README.md
- com_002_airports/README.md
- com_007_rw1_fdi_regulatory_restrictiveness_index/README.md
- com_017_rw2_major_ports/README.md
- ene_001a_reservoirs_and_dams/README.md
- ene_033_energy_consumption/README.md
- ene_034_electricity_consumption/README.md
- for_029_peatlands/README.md
- ocn_001_gebco_bathymetry/README.md
- soc_004_rw1_human_development_index/README.md
- soc_005_rw1_political_rights_civil_liberties_index/README.md
- soc_025a_gender_inequality_index/README.md
- soc_091_global_peace_index/README.md
- soc_092_positive_peace_index/README.md
- soc_093_global_terrorism_index/README.md
- wat_026_rw1_wastewater_treatment_plants/README.md
- wat_036_rw1_water_stress_country_ranking/README.md
- wat_064_cost_of_sustainable_water_management/README.md
this is a test run of the github repo editor tool
> update all http links in readme files

- ocn_006alt_projected_ocean_acidification_coral_reefs/README.md
- ocn_006alt_projected_ocean_acidification_coral_reefs/ocn_006alt_projected_ocean_acidification_coral_reefs.py
- utils/util_files.py
> ocn.006alt

- ocn_014_index_of_coastal_protection_by_coral_reefs/README.md
- ocn_014_index_of_coastal_protection_by_coral_reefs/ocn_014_index_of_coastal_protection_by_coral_reefs.py
> script & readme

- dis_017_storm_events_us/README.md
- dis_017_storm_events_us/dis_017_storm_events_us_processing.py
> Adding read_me dis.017 pre-processing

- dis_017_storm_events_us/README.md
- dis_017_storm_events_us/dis_017_storm_events_us_processing.py
> updating aws issue solved

- wat_065_rw0_hydropoli_tension_and_institu_vulnerability/README.md
- wat_065_rw0_hydropoli_tension_and_institu_vulnerability/wat_065_rw0_hydropoli_tension_and_institu_vulnerability_processing.py
> Wat 065 rw0 hydropolitical tension processing

- utils/util_carto.py
> add additional comments to util_carto

- com_028_rw1_effect_of_ag_prices_on_commodity_prices/README.md
- com_028_rw1_effect_of_ag_prices_on_commodity_prices/com_028_rw1_effect_of_ag_prices_on_commodity_prices_processing.py
> creating script for com_028_rw1

- foo_041_rw1_non_co2_agricultural_emissions/README.md
- foo_041_rw1_non_co2_agricultural_emissions/foo_041_rw1_non_co2_agricultural_emissions_processing.py
> Foo 041 rw1

- ene_017_rw1_energy_facility_emissions/README.md
- ene_017_rw1_energy_facility_emissions/ene_017_rw1_energy_facility_emissions_processing.py
> creating script for ene_017

- soc_045_rw1_women_political_representation/README.md
- soc_045_rw1_women_political_representation/soc_045_rw1_women_political_representation_processing.py
> adding script for soc_045

- com_028_rw1_effect_of_ag_prices_on_commodity_prices/README.md
- com_028_rw1_effect_of_ag_prices_on_commodity_prices/com_028_rw1_effect_of_ag_prices_on_commodity_prices_processing.py
> subset com_028_rw1

- com_015_rw1_recycling_rates/README.md
- com_015_rw1_recycling_rates/com_015_rw1_recycling_rates_processing.py
> Create script for com.015.rw1

- com_015_rw1_recycling_rates/README.md
- soc_039_rw1_out_of_school_rate/README.md
- soc_039_rw1_out_of_school_rate/soc_039_rw1_out_of_school_rate_processing.py
> Soc 039 rw1

- foo_041_rw1_non_co2_agricultural_emissions/README.md
- foo_041_rw1_non_co2_agricultural_emissions/foo_041_rw1_non_co2_agricultural_emissions_processing.py
> including only country level data

- dis_016_rw1_active_fault_lines/README.md
- dis_016_rw1_active_fault_lines/dis_016_rw1_active_fault_lines_processing.py
> create script for dis.016.rw1

- soc_048_rw0_organized_violence_events/README.md
- soc_048_rw0_organized_violence_events/soc_048_rw0_organized_violence_events_processing.py
> Soc 048 rw0 organized violence events

- soc_049_rw0_water_conflict_map/README.md
- soc_049_rw0_water_conflict_map/soc_049_rw0_water_conflict_map_processing.py
> Soc 049 rw0 water conflict map

- utils/util_carto.py
> Edit util carto

- for_005a_mangrove/.vscode/settings.json
- for_005a_mangrove/for_005a_mangrove_processing.py
- utils/util_carto.py
> For 005 fix

- soc_085_rw1_elevation/README.md
- soc_085_rw1_elevation/soc_085_rw1_elevation_processing.py
> create script for soc.085.rw1

- foo_054_rw1_soil_carbon_stocks/README.md
> add README for foo.054.rw1

- utils/util_carto.py
> add tagging to carto util

- utils/util_carto.py
> Fixing line in upload_carto

- wat_008_rw3_annual_surface_water_coverage/README.md
> add readme file

- cli_050-059_066-075_nexgddp_and_loca/cli_050-059_066-075_nexgddp_and_loca_processing.py
> initial commit

- cli_050-059_066-075_nexgddp_and_loca/README.md
> Nex commit

- wat_039_rw0_wetlands/README.md
- wat_039_rw0_wetlands/wat_039_rw0_wetlands_processing.py
> create script for wat.039.rw0

- soc_104_rw0_global_land_cover/README.md
> soc.104 readme

- soc_049_rw0_water_conflict_map/README.md
> fixed typo

- cli_050-059_066-075_nexgddp_and_loca/README.md
- cli_050-059_066-075_nexgddp_and_loca/cli_050-059_066-075_nexgddp_and_loca_processing.py
> add s3 upload

- com_011_rw1_maritime_boundaries/README.md
- com_011_rw1_maritime_boundaries/com_011_rw1_maritime_boundaries_processing.py
- utils/util_carto.py
> create script for com.011.rw1

- utils/util_cloud.py
> Update gee_ingest() function in util_cloud.py

- for_021_rw1_certified_forest/README.md
- for_021_rw1_certified_forest/for_021_rw1_certified_forest_processing.py
> adding readme

- soc_048_rw0_organized_violence_events/README.md
- soc_048_rw0_organized_violence_events/soc_048_rw0_organized_violence_events_processing.py
> add 2020 data

- for_014_rw1_internationally_important_wetlands/README.md
- for_014_rw1_internationally_important_wetlands/for_014_rw1_internationally_important_wetlands_processing.py
> create script for updating the dataset

- foo_061_rw0_blue_food_supply/foo_061_rw0_blue_food_supply_processing.py
> Foo 061 updates

- foo_015_rw2_global_hunger_index/README.md
- foo_015_rw2_global_hunger_index/foo_015_rw2_global_hunger_index_processing.py
> update script for 2021 data

- utils/util_files.py
> update import gdal

- foo_005_rw1_crop_area_production/README.md
- foo_005_rw1_crop_area_production/foo_005_rw1_crop_area_production_processing.py
> Foo 005 rw1

- foo_068_rw0_agro_ecological_zones/README.md
- foo_068_rw0_agro_ecological_zones/foo_068_rw0_agro_ecological_zones_processing.py
- utils/util_cloud.py
> Foo 068 rw0

- foo_068_rw0_agro_ecological_zones/README.md
- foo_068_rw0_agro_ecological_zones/foo_068_rw0_agro_ecological_zones_processing.py
> foo_068_rw0 AEZ Data Processing for CRT

- foo_069_rw0_relative_change_crop_yield/README.md
- foo_069_rw0_relative_change_crop_yield/foo_069_rw0_relative_change_crop_yield_processing.py
> Foo 069 rw0

- foo_069_rw0_relative_change_crop_yield/README.md
- foo_069_rw0_relative_change_crop_yield/foo_069_rw0_relative_change_crop_yield_processing.py
> foo_069_rw0 Relative Change in Crop Yield for CRT

- cit_043_rw0_bus_rapid_transit/README.md
- cli_008_greenhouse_gas_emissions_country_sector/README.md
- dis_017_storm_events_us/README.md
- ene_017_rw1_energy_facility_emissions/README.md
- foo_041_rw1_non_co2_agricultural_emissions/README.md
- foo_060_rw0_food_system_emissions/README.md
- foo_061_rw0_blue_food_supply/README.md
- foo_062_rw0_fishery_production/README.md
- foo_066_rw0_food_product_shares/README.md
- foo_067_rw0_crop_suitability_class/README.md
- foo_067_rw0_crop_suitability_class/foo_067_rw0_crop_suitability_class_processing.py
- for_021_rw1_certified_forest/README.md
- ocn_001_gebco_bathymetry/README.md
- ocn_013_coral_reef_fisheries_relative_catch/README.md
- ocn_014_index_of_coastal_protection_by_coral_reefs/README.md
- soc_002_rw1_gender_development_index/README.md
- soc_023_rw1_fragile_states_index/README.md
- soc_043_rw0_refugees_internally_displaced_persons/README.MD
- soc_045_rw1_women_political_representation/README.md
- soc_086_subnational_hdi/README.md
- wat_070_rw0_soil_erosion/README.md
> Foo 067 rw0

- foo_067_rw0_crop_suitability_class/README.md
- foo_067_rw0_crop_suitability_class/foo_067_rw0_crop_suitability_class_processing.py
> GAEZv4 Crop Suitability Class Processing

- cli_029a_vulnerability_to_climate_change/README.md
- cli_029a_vulnerability_to_climate_change/cli_029a_vulnerability_to_climate_change_processing.py
> cli_029a Vulnerability to Climate Change Updates for CRT

- com_039_rw0_agricultural_trade_statistics/README.md
- com_039_rw0_agricultural_trade_statistics/com_039_rw0_agricultural_trade_statistics_processing.py
> com_039_rw0 upload table to Carto & S3. Add myself to readme.

- foo_005_rw1_crop_area_production/README.md
- foo_005_rw1_crop_area_production/foo_005_rw1_crop_area_production_processing.py
> foo_005_rw1 Adding Crops and Yield data for CRT

- soc_108_rw0_anthropogenic_biomes/README.md
> add readme

- com_039_rw0_agricultural_trade_statistics/README.md
- com_039_rw0_agricultural_trade_statistics/com_039_rw0_agricultural_trade_statistics_processing.py
> remove records without value

- foo_067_rw0_crop_suitability_class/create-stats-table-for-crt-widget.py
- foo_067_rw0_crop_suitability_class/create_stats_table_for_crt_widget.py
This script processes and returns stats from the Crop Suitability rasters that are currently on [Resource Watch](https://resourcewatch.org/data/explore/945185f8-76b5-4f4d-84d6-eff7f96dd1f3?section=Discover&selectedCollection=&zoom=3&lat=1.3182430568630186&lng=7.294921874998732&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522945185f8-76b5-4f4d-84d6-eff7f96dd1f3%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522c90e0cf7-442a-4410-b7ce-411202ecc420%2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1) for the CRT site. One CSV is output and is to be uploaded to Carto DB, so a stacked bar chart widget can be created.
> CRT - Processing script for Crop Suitability stacked bar chart widget
